### ISSUE TITLE
META Issues

### ISSUE THREAD

**Issue by TheDoctor1977** [Guloveos/arc-station-14#9]
- [ ] Hardsuit has 30% heat resist, should be 70%
- [ ] The helmet says "helment" and is also not capitalized
- [ ] The job title has underscores (Urban_Solutions_Scenario_Manager)
- [ ] The ID also has no name, which when combined with the above issue leads to this: 
![image](https://github.com/user-attachments/assets/6de00e1b-d664-43df-a383-1f711a7d419d)
- [ ] Merc radio should be "UrbSol"
- [ ] This is not a bug, but I would like a few combat medipens and burn/brute autoinjectors included in the bag
- [ ] There is NO capitalization, and you spelled capture wrong!!!! I can't even be bothered to crop this one because of how much you have failed me, Guloveos
![image](https://github.com/user-attachments/assets/f41c5b69-7693-4478-8e94-468713e8e419)

**Comment by Guloveos** [comment]
all done

**Comment by TheDoctor1977** [comment]
not fixed on the server, if this has been done, please push the update to the testing server and reopen this

**Comment by TheDoctor1977** [comment]
ITS STILL NOT ON THE SERVER RAHHHHH
